package com.murat.murat.sontaxi;

/**
 * Created by murat on 13.05.2017.
 */

public class SehirChange {
    public String dbToString(String sehir) {

        switch (sehir) {

             case "Adana":
                return "ADANA";
            case "Adıyaman":
                return "ADIYAMAN";
            case "Afyonkarahisar":
                return "AFYONKARAHİSAR";
            case "AğrI":
                return "AGRI";
            case "Aksaray":
                return "AKSARAY";
            case "Amasya":
                return "AMASYA";
            case "Ankara":
                return "ANKARA";
            case "Antalya":
                return "ANTALYA";
            case "Ardahan":
                return "ARDAHAN";
            case "Artvin":
                return "ARTVIN";
            case "Aydın":
                return "AYDIN";
            case "Balıkesir":
                return "BALIKESIR";
            case "Bartin":
                return "BARTIN";
            case "Batman":
                return "BATMAN";
            case "Bayburt":
                return "BAYBURT";
            case "Bilecik":
                return "BILECIK";
            case "Bingöl":
                return "BINGOL";
            case "Bitlis":
                return "BITLIS";
            case "Bolu":
                return "BOLU";
            case "Burdur":
                return "BURDUR";
            case "Bursa":
                return "BURSA";
            case "Çanakkale":
                return "CANAKKALE";
            case "Çankırı":
                return "CANKIRI";
            case "Çorum":
                return "CORUM";
            case "Denizli":
                return "DENIZLI";
            case "Diyarbakir":
                return "DIYARBAKIR";
            case "Düzce":
                return "DUZCE";
            case "Edirne":
                return "EDIRNE";
            case "Elazığ":
                return "ELAZIG";
            case "Erzincan":
                return "ERZINCAN";
            case "Erzurum":
                return "ERZURUM";
            case "Eskişehir":
                return "ESKİSEHİR";
            case "Gaziantep":
                return "GAZIANTEP";
            case "Giresun":
                return "GIRESUN";
            case "Gümüşhane":
                return "GUMUSHANE";
            case "Hakkari":
                return "HAKKARI";
            case "Hatay":
                return "HATAY";
            case "Igdır":
                return "IGDIR";
            case "Isparta":
                return "ISPARTA";
            case "İstanbul":
                return "ISTANBUL";
            case "İzmir":
                return "IZMIR";
            case "Kahramanmaraş":
                return "KAHRAMANMARAS";
            case "Karabük":
                return "KARABUK";
            case "Karaman":
                return "KARAMAN";
            case "Kars":
                return "KARS";
            case "Kastamonu":
                return "KASTAMONU";
            case "Kayseri":
                return "KAYSERI";
            case "Kilis":
                return "KILIS";
            case "Kirikkale":
                return "KIRIKKALE";
            case "Kırklareli":
                return "KIRKLARELI";
            case "Kırşehir":
                return "KIRSEHİR";
            case "Kocaeli":
                return "KOCAELİ";
            case "Konya":
                return "KONYA";
            case "Kütahya":
                return "KUTAHYA";
            case "Malatya":
                return "MALATYA";
            case "Mardin":
                return "MARDIN";
            case "Manisa":
                return "MANISA";
            case "Mersin":
                return "MERSIN";
            case "Muğla":
                return "MUGLA";
            case "Muş":
                return "MUS";
            case "Nevşehir":
                return "NEVSEHIR";
            case "Niğde":
                return "NIGDE";
            case "Ordu":
                return "ORDU";
            case "Osmaniye":
                return "OSMANIYE";
            case "Rize":
                return "RIZE";
            case "Sakarya":
                return "SAKARYA";
            case "Samsun":
                return "SAMSUN";
            case "Sanliurfa":
                return "SANLIURFA";
            case "Siirt":
                return "SIIRT";
            case "Sinop":
                return "SINOP";
            case "Şirnak":
                return "SIRNAK";
            case "Sivas":
                return "SIVAS";
            case "Tekirdağ":
                return "TEKIRDAG";
            case "Tokat":
                return "TOKAT";
            case "Trabzon":
                return "TRABZON";
            case "Tunceli":
                return "TUNCELI";
            case "Usak":
                return "USAK";
            case "Van":
                return "VAN";
            case "Yalova":
                return "YALOVA";
            case "Yozgat":
                return "YOZGAT";
            case "Zonguldak":
                return "ZONGULDAK";
            case "null" :  return "ADANA";
        }
        return sehir;
    }

}
